import React from 'react';
import Hero from '@/components/Hero';
import FeaturedProducts from '@/components/FeaturedProducts';
import TrendingProducts from '@/components/TrendingProducts';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Cosmetic Shop",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <Hero />
      <FeaturedProducts />
      <TrendingProducts />
    </div>
  );
}
